{
 "title": "Viessmann Gas Boiler",
 "description": "Dashboard of Viessmann Gas Buoiler exporter\nhttps://github.com/zbitmanis/viessman-prometheus",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "Datasource", "query": "prometheus" },
   {
    "name": "installation",
    "label": "installation",
    "query": {
     "query": "label_values(viessmann_heating_dhw_temperature,installation_id)"
    }
   },
   {
    "name": "gateway",
    "label": "gateway serial",
    "query": {
     "query": "label_values(viessmann_heating_dhw_temperature,gateway_id)"
    }
   },
   {
    "name": "device",
    "label": "device",
    "query": {
     "query": "label_values(viessmann_heating_dhw_temperature,device_id)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Viessmann API server data quality (Latest Data on API Server Age  | Collector Data Age | Prometheus Scrape Metrics Age)",
   "type": "stat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time()-viessmann_heating_collector_data_timestamp{request=\"features\", type=\"api\"}\nunless \nviessmann_heating_collector_data_timestamp{request=\"features\", metric=~\".+\"}",
     "legendFormat": "API Data Age"
    },
    {
     "expr": "time()-viessmann_heating_collector_data_timestamp{request=\"features\", type=\"collector\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "time() - timestamp(viessmann_heating_collector_data_timestamp{request=\"features\",type=\"api\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Outside temperature",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "viessmann_heating_environment_temperature_outside\nor \nviessmann_sensors_temperature_out",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Outside Temperature",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 18, "x": 6, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "viessmann_heating_environment_temperature_outside\nor \nviessmann_sensors_temperature_out",
     "legendFormat": "outside temperature"
    }
   ]
  },
  {
   "title": "Todays gas consumption",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "m3" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "legendFormat": "__auto" },
    {
     "expr": "viessmann_heating_energy_gas_consumption_cbm{period=\"day\", feature=\"dhw\"}",
     "legendFormat": "{{feature}}"
    },
    {
     "expr": "viessmann_heating_energy_gas_consumption_cbm{period=\"day\", feature=\"heating\"}",
     "legendFormat": "{{feature}}"
    },
    {
     "expr": "sum(viessmann_heating_energy_gas_consumption_cbm{period=\"day\"})",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Gas consumption daily",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 18, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "m3" } },
   "targets": [
    {
     "expr": "max(viessmann_heating_energy_gas_consumption_cbm{period=\"day\", feature=\"dhw\"}\nor\nviessmann_heating_gas_consumption_cbm{period=\"day\", feature=\"dhw\"})",
     "legendFormat": "{{feature}}"
    },
    {
     "expr": "max(viessmann_heating_energy_gas_consumption_cbm{period=\"day\", feature=\"heating\"}\nor\nviessmann_heating_gas_consumption_cbm{period=\"day\", feature=\"heating\"})",
     "legendFormat": "{{feature}}"
    },
    {
     "expr": "sum by () (\n\n    viessmann_heating_energy_gas_consumption_cbm{period=\"day\"}\n    or\n    viessmann_heating_gas_consumption_cbm{period=\"day\"}\n)",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Gas consumption daily (summary for previous days)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 18, "x": 6, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "m3" } },
   "targets": [
    {
     "expr": "max_over_time(\n    viessmann_heating_energy_gas_consumption_cbm{period=\"day\", feature=\"dhw\"}[1d]\n    )\n\nor \nmax_over_time(\n    viessmann_heating_gas_consumption_cbm{period=\"day\", feature=\"dhw\"}[1d]\n    )\n",
     "legendFormat": "{{feature}}"
    },
    {
     "expr": "max_over_time(viessmann_heating_energy_gas_consumption_cbm{period=\"day\", feature=\"heating\"}[1d])\nor \nmax_over_time(viessmann_heating_gas_consumption_cbm{period=\"day\", feature=\"heating\"}[1d])",
     "legendFormat": "{{feature}}"
    },
    {
     "expr": "sum by () (\n  max_over_time(\n    viessmann_heating_energy_gas_consumption_cbm{period=\"day\"}[1d]\n  )\n  or \n  max_over_time(\n    viessmann_heating_gas_consumption_cbm{period=\"day\"}[1d]\n  )\n)",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Monthly  gas consumption",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "m3" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "legendFormat": "__auto" },
    {
     "expr": "viessmann_heating_energy_gas_consumption_cbm{period=\"month\", feature=\"dhw\"}",
     "legendFormat": "{{feature}}"
    },
    {
     "expr": "viessmann_heating_energy_gas_consumption_cbm{period=\"month\", feature=\"heating\"}",
     "legendFormat": "{{feature}}"
    },
    {
     "expr": "sum(viessmann_heating_energy_gas_consumption_cbm{period=\"month\"})",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Yearly  gas consumption",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "m3" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "legendFormat": "__auto" },
    {
     "expr": "viessmann_heating_energy_gas_consumption_cbm{period=\"year\", feature=\"dhw\"}",
     "legendFormat": "{{feature}}"
    },
    {
     "expr": "viessmann_heating_energy_gas_consumption_cbm{period=\"year\", feature=\"heating\"}",
     "legendFormat": "{{feature}}"
    },
    {
     "expr": "sum(viessmann_heating_energy_gas_consumption_cbm{period=\"year\"})",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Todays electricity consumption",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "legendFormat": "__auto" },
    {
     "expr": "viessmann_heating_energy_power_consumption_kwh{period=\"day\", feature=\"dhw\"}",
     "legendFormat": "{{feature}}"
    },
    {
     "expr": "viessmann_heating_energy_power_consumption_kwh{period=\"day\", feature=\"heating\"}",
     "legendFormat": "{{feature}}"
    },
    {
     "expr": "sum(viessmann_heating_energy_power_consumption_kwh{period=\"day\"})",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Electricity consumption daily (summary for previous days)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 18, "x": 6, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "expr": "max_over_time(viessmann_heating_energy_power_consumption_kwh{period=\"day\", feature=\"dhw\"}[1d])\nor \nmax_over_time(viessmann_heating_power_consumption_kwh{period=\"day\", feature=\"dhw\"}[1d])",
     "legendFormat": "{{feature}}"
    },
    {
     "expr": "max_over_time(viessmann_heating_energy_power_consumption_kwh{period=\"day\", feature=\"heating\"}[1d])\nor \nmax_over_time(viessmann_heating_power_consumption_kwh{period=\"day\", feature=\"heating\"}[1d])",
     "legendFormat": "{{feature}}"
    },
    {
     "expr": "sum by () (\n  max_over_time(\n    viessmann_heating_energy_power_consumption_kwh{period=\"day\"}[1d]\n  )\n) or \nsum by () (\n  max_over_time(\n    viessmann_heating_power_consumption_kwh{period=\"day\"}[1d]\n  )\n)",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Monthly electricity consumption",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "legendFormat": "__auto" },
    {
     "expr": "viessmann_heating_energy_power_consumption_kwh{period=\"month\", feature=\"dhw\"}",
     "legendFormat": "{{feature}}"
    },
    {
     "expr": "viessmann_heating_energy_power_consumption_kwh{period=\"month\", feature=\"heating\"}",
     "legendFormat": "{{feature}}"
    },
    {
     "expr": "sum(viessmann_heating_energy_power_consumption_kwh{period=\"month\"})",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Yearly electricity consumption",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "legendFormat": "__auto" },
    {
     "expr": "viessmann_heating_energy_power_consumption_kwh{period=\"year\", feature=\"dhw\"}\nor\nviessmann_heating_power_consumption_kwh{period=\"year\", feature=\"dhw\"}\n",
     "legendFormat": "{{feature}}"
    },
    {
     "expr": "viessmann_heating_energy_power_consumption_kwh{period=\"year\", feature=\"heating\"}\nor\nviessmann_heating_power_consumption_kwh{period=\"year\", feature=\"heating\"}",
     "legendFormat": "{{feature}}"
    },
    {
     "expr": "sum(viessmann_heating_energy_power_consumption_kwh{period=\"year\"})\nor \nsum(viessmann_heating_power_consumption_kwh{period=\"year\"})",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Todays Viessmann heating production summary (kWh)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "legendFormat": "__auto" },
    {
     "expr": "viessmann_heating_energy_production_kwh{period=\"day\", feature=\"dhw\"}",
     "legendFormat": "{{feature}}"
    },
    {
     "expr": "viessmann_heating_energy_production_kwh{period=\"day\", feature=\"heating\"}",
     "legendFormat": "{{feature}}"
    },
    {
     "expr": "sum(viessmann_heating_energy_production_kwh{period=\"day\"})",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Viessmann heating production daily (kWh) -summary for previous days",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 18, "x": 6, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "expr": "max(max_over_time(viessmann_heating_energy_production_kwh{period=\"day\", feature=\"dhw\"}[1d])\nor \nmax_over_time(viessmann_heating_production_consumption_kwh{period=\"day\", feature=\"dhw\"}[1d]))\n",
     "legendFormat": "{{feature}}"
    },
    {
     "expr": "max(max_over_time(viessmann_heating_energy_production_kwh{period=\"day\", feature=\"heating\"}[1d]) \n    or \n    max_over_time(viessmann_heating_production_consumption_kwh{period=\"day\", feature=\"heating\"}[1d]) \n    )",
     "legendFormat": "{{feature}}"
    },
    {
     "expr": "sum by () (\n  max_over_time(\n    viessmann_heating_energy_production_kwh{period=\"day\"}[1d]\n  )\n  or \n   max_over_time(\n    viessmann_heating_production_consumption_kwh{period=\"day\"}[1d]\n  )\n)",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Preassure",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "pressurebar" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "viessmann_heating_boiler_pressure",
     "legendFormat": "dhw"
    }
   ]
  },
  {
   "title": "Supply Pressure",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 18, "x": 6, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "pressurebar" } },
   "targets": [
    {
     "expr": "min( viessmann_sensors_preasure  or viessmann_heating_boiler_pressure)",
     "legendFormat": "supply pressure"
    }
   ]
  },
  {
   "title": "Boiler temperature",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "viessmann_heating_boiler_sensors_temperature",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Boiler Temperature",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 18, "x": 6, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "viessmann_heating_boiler_sensors_temperature",
     "legendFormat": "boiler temperature"
    }
   ]
  },
  {
   "title": "Circuits temperature",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "viessmann_heating_circuit_temperature",
     "legendFormat": "{{feature}}"
    }
   ]
  },
  {
   "title": "Circuits Temperature",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 18, "x": 6, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "viessmann_heating_circuit_temperature \nor \nviessmann_heating_circuits_temperature",
     "legendFormat": "circuit: {{feature}}"
    }
   ]
  },
  {
   "title": "DHW temperature",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "viessmann_heating_dhw_sensors_temperature",
     "legendFormat": "dhw"
    }
   ]
  },
  {
   "title": "DHW Temperature",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 18, "x": 6, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "viessmann_heating_dhw_sensors_temperature",
     "legendFormat": "{{feature}}"
    }
   ]
  },
  {
   "title": "Viessmann API server data age",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "time()-viessmann_heating_collector_data_timestamp{request=\"features\"}\nunless \nviessmann_heating_collector_data_timestamp{request=\"features\", metric=~\".+\"}",
     "legendFormat": "{{type}}"
    },
    {
     "expr": "time()-max(timestamp(viessmann_heating_collector_data_timestamp{request=\"features\"}))\nunless \nviessmann_heating_collector_data_timestamp{request=\"features\", metric=~\".+\"}",
     "legendFormat": "scrape"
    }
   ]
  },
  {
   "title": "API Data quality",
   "type": "timeseries",
   "description": "Data age on the  Viessmann API server during data fetch",
   "gridPos": { "h": 6, "w": 18, "x": 6, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "time()-viessmann_heating_collector_data_timestamp{request=\"features\", type=\"api\"}",
     "legendFormat": "api data age: {{request}}-{{type}}"
    },
    {
     "expr": "time()-viessmann_heating_collector_data_timestamp{request=\"features\", type=\"collector\"}",
     "legendFormat": "api data age: {{request}}-{{type}}"
    },
    {
     "expr": "time() - timestamp(viessmann_heating_collector_data_timestamp{request=\"features\",type=\"api\"}) ",
     "legendFormat": "api data age: scrape"
    }
   ]
  },
  {
   "title": "Viessmann API collector features stats",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 67 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "viessmann_heating_collector_metrics_stats{request=\"features\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Collector  Data quality",
   "type": "timeseries",
   "description": "Data age on the  Viessmann API server during data fetch",
   "gridPos": { "h": 5, "w": 18, "x": 6, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "viessmann_heating_collector_metrics_stats{request=\"features\"}",
     "legendFormat": "metrics: {{request}}-{{type}}"
    }
   ]
  }
 ]
}